[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[edge_functions]]
  pattern = "/*"
  excludedPattern = [
    "/public/books/covers/*",
    "/books/covers/*",
  ]
  function = "*"
